- name: check the facts
  hosts: local
  connection: local

  tasks:
    - name: install nginx on RedHat family
      ansible.builtin.dnf:
        name: nginx
        state: latest
      when: ansible_os_family == "RedHat"

    - name: install nginx on Debian family
      ansible.builtin.apt:
        name: nginx
        state: latest
      when: ansible_os_family == "Debian"