- name: install packages
  hosts: local
  connection: local
  tasks:
  - name: install the packages using loop at time
    ansible.builtin.package:
       name: "{{ iteam }}"
    loop:
      - nginx
      - mysql
      - zip
    