- name: nginx install and start
  hosts: localhost
  tasks:
  - name: install nginx
    ansible.builtin.yum:
      name: nginx
      state: present

  - name: start nginx
    ansible.builtin.service:
     name: nginx
     state: started
     enabled: true    