- name: varible promot
  hosts: localhost
  connection: local
  vars_prompt:
  - name: username
    prompt: what is your username
    private: false
  - name: password
    prompt: what is your password
    private: true  
  tasks:
  - name: print the username
    ansible.builtin.debug:
      msg: "hello {{ username }}, {{ password}}"   